services:
  narou:
    build:
      context: .
      dockerfile: dockerfile
      args:
        NAROU_VERSION: 3.9.1
        AOZORAEPUB3_VERSION: 1.1.1b26Q
        UID: 3007
        GID: 3003
    image: kokotaro/narou:3.9.1
    command: ["narou", "web", "-np", "33000"]
    volumes:
      - /mnt/DatenSSD/Daten/narou:/home/narou/novel:cached
    tty: true
    stdin_open: true
    ports:
      - 9200:33000
      - 9201:33001
